import asyncio
from app.db.pool import init_pool, close_pool, get_connection

async def create_payment_notifications_table():
    await init_pool()
    async with get_connection() as conn:
        await conn.execute("""
            CREATE TABLE IF NOT EXISTS system.admin_payment_msgs (
                id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                order_id    INTEGER NOT NULL,
                admin_telegram_id BIGINT NOT NULL,
                message_id  BIGINT NOT NULL,
                created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                UNIQUE(admin_telegram_id, message_id)
            );
        """)
        print("Tabla system.admin_payment_msgs creada exitosamente.")
    await close_pool()

asyncio.run(create_payment_notifications_table())
